# Generated by Django 5.1.7 on 2025-03-11 21:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_participant_last_seen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='participant',
            name='guest_identifier',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'game_session'), name='unique_user_session'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('guest_identifier', 'game_session'), name='unique_guest_session'),
        ),
    ]
