# Generated by Django 5.1.7 on 2025-03-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_participant_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='guest_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
