# Generated by Django 5.1.7 on 2025-03-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_participant_guest_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='host',
        ),
        migrations.AddField(
            model_name='participant',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
    ]
