# Generated by Django 5.1.7 on 2025-03-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_gamesession_host_participant_is_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='secret',
            field=models.CharField(default='6004fa4bea6941ed8d2578e927de0820', max_length=64),
        ),
    ]
