# Generated by Django 5.1.7 on 2025-03-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_participant_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='secret',
            field=models.CharField(default='81bf2e0c0cd34d08b27b0481b9cd0956', max_length=64),
        ),
    ]
