# Generated by Django 5.1.7 on 2025-03-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_participant_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='secret',
            field=models.CharField(default='82bfd87af6f742f7b86d6db6e557936c', max_length=64),
        ),
    ]
