# Generated by Django 5.1.7 on 2025-03-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_participant_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='secret',
            field=models.CharField(default='e0c6f786e00141ac9278a0265b19538a', max_length=64),
        ),
    ]
