# Generated by Django 5.1.7 on 2025-03-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_participant_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='secret',
            field=models.CharField(default='eca24ddda2a646e0b8ed8c3cbb4e68c3', max_length=64),
        ),
    ]
