# Generated by Django 5.1.7 on 2025-03-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_participant_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='secret',
            field=models.CharField(default='f2d5e3287f6f4a549ef10f653b3e3547', max_length=64),
        ),
    ]
