# Generated by Django 5.1.7 on 2025-03-19 19:03

import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_participant_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='secret',
            field=models.CharField(default=game.models.generate_secret, max_length=64),
        ),
    ]
