# Generated by Django 5.1.7 on 2025-03-24 11:26

import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_alter_participant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=game.models.get_character_image_upload_path),
        ),
    ]
