# Generated by Django 5.1.7 on 2025-03-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_participant_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('guessing', 'Guessing'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
