# Generated by Django 5.1.7 on 2025-03-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_alter_gamesession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='guess_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='guess_timer',
            field=models.IntegerField(default=60),
        ),
    ]
