# Generated by Django 5.1.7 on 2025-04-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_gamesession_guess_deadline_gamesession_guess_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('chat', 'Chat'), ('system', 'System')], default='chat', max_length=10),
        ),
    ]
