# Generated by Django 5.2 on 2025-04-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_message_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_public',
            field=models.BooleanField(default=False, help_text='True for seeded/public characters, False for user-private ones'),
        ),
    ]
