# Generated by Django 5.2 on 2025-04-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_question_deleted_at_question_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_npc',
            field=models.BooleanField(default=False),
        ),
    ]
