# Generated by Django 5.2 on 2025-05-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_participant_is_npc'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='npc_sequence',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
