# Generated by Django 5.2 on 2025-05-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_gamesession_npc_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='ai_context',
            field=models.TextField(blank=True, default='', help_text='Additional context for AI participants'),
        ),
    ]
